### ISSUE TITLE
Non-latin characters in PelEntryWindowsString

### ISSUE THREAD

**Issue by mage2pro** [lsolesen/pel#16]
Why does PelEntryWindowsString support only Latin-1 character set?
Windows surely supports other ASCII character sets in file properties dialog (particularly, russian: Windows-1251).

**Comment by lsolesen** [comment]
@mage2pro Do you know whether Windows has started supporting UTF-8. It's been a while, so I think (hope) they may support it now?

**Comment by lsolesen** [comment]
Closing this for now. Please reopen, if you still have this problem.
