### ISSUE TITLE
Some PelInvalidDataException if I´m trying to read a Jpeg exported with Ligtroom 3

### ISSUE THREAD

**Issue by SunboX** [lsolesen/pel#18]
Hi,

if I´m trying to read Exif Data of this image:

http://dl.dropbox.com/u/6037571/exif/_MG_7264.jpg

I´m getting some PelInvalidDataExceptions and some infos like tags / comments are missing.
I´ve exported this image using Photoshop Lightroom 3. Hope that helps, btw love your library! :o)

greetings André

**Comment by lsolesen** [comment]
@SunboX I am going to close this for now. Lightroom 3 is probably not being used much anymore - and the ressources are not available anymore.
