### ISSUE TITLE
'...Should be compatible with...'

### ISSUE THREAD

**Issue by machouinard** [lsolesen/pel#23]
PEL is working great for me, however I just added some error handling to the site I'm building and can't figure this out.  Every time any of my pages that use PEL are loaded, I get these errors:

    PelEntryUndefined.php' on line 285: Declaration of PelEntryUserComment::setValue() should be compatible with that of PelEntryUndefined::setValue()

    PelEntryUndefined.php' on line 414: Declaration of PelEntryVersion::setValue() should be compatible with that of PelEntryUndefined::setValue()
  
    PelEntryAscii.php' on line 559: Declaration of PelEntryCopyright::setValue() should be compatible with that of PelEntryAscii::setValue()

    PelEntryNumber.php' on line 307: Declaration of PelEntryNumber::setValue() should be compatible with that of PelEntry::setValue()

I can read and write EXIF just fine, but even after days of endlessly searching the web, I can't figure out what is going on.  On my gallery page, all it does it read EXIF.  Why are the errors regarding setValue()?  I found a post about these exact messages from 2008, but I didn't see a solution.  I'm very new to this, so forgive me if I've missed something elementary.   Here is the PEL code from the gallery page if it helps:

    //////////////////////EXIF PROCESSING//////////////////////////////////
    $data = new PelDataWindow($pic);
    if (PelJpeg::isValid($data)) {
        $pJpg = new PelJpeg($pic);
        $exif = $pJpg->getExif();
        if ($exif != null){//if there is exif data
            $tiff = $exif->getTiff();
            $ifd0 = $tiff->getIfd();
            //sub ifds
            $ifd0_0 = $ifd0->getSubIfd(PelIfd::EXIF); // IFD Exif
            if($entry = $ifd0_0->getEntry(PelTag::DATE_TIME_ORIGINAL)){
                $time1 = $entry->getValue();//if exif includes original date and time
                $eDate = date( "M d, Y", $time1)." (date taken)";
            }else{
                $eDate = $newDate;	
            }
        }
    }
    //////////////////////DONE EXIF PROCESSING/////////////////////////////

Sorry for the bother, but thanks very much for any help.  Even a shove in the right direction would be a good start for me!

**Comment by weberhofer** [comment]
Those issues should all be fixed now.
