### ISSUE TITLE
Image Title and Location ?

### ISSUE THREAD

**Issue by rusuandreirobert** [lsolesen/pel#39]
Hey there, I'm really sorry for posting this, but I'm simply going nuts already, I'm trying to re-arrange a photo library, and I have no idea, absolutelly, no idea how to get this working to change the title.
The GPS data was really simple, the example helped, a lot, and I really mean it. 
But how can I change the image title ? and SUBJECT_Location, I've already tried working this out for the past 2 days and I simply can't get it working. Any hints would help & mean a lot.

Any suggestions or tips on how I can achieve this ? I'm simply out of ideas.

I've read & noticed this isn't maintained by the original creator, and used anymore, but maybe someone can take a few minutes and help a desperate guy here :).
I couldn't actually get more than it's already in the documents, i've tried A LOT of other things, such as IPTC information and such, but nothing lets me achieve my end goal, which is displaying the right info when using the "Get Image Info" on MAC & Windows. 

* Description and GeoLocation data are working perfect.

```
function addFullInformation(
    $input, $output,
    $title, $location, $description, $keywords,
    $longitude, $latitude, $altitude, $date_time) {
  $jpeg = new PelJpeg($input);

  $exif = new PelExif();
  $jpeg->setExif($exif);

  $tiff = new PelTiff();
  $exif->setTiff($tiff);

  $ifd0 = new PelIfd(PelIfd::IFD0);
  $tiff->setIfd($ifd0);

  $inter_ifd = new PelIfd(PelIfd::INTEROPERABILITY);
  $ifd0->addSubIfd($inter_ifd);

  $ifd0->addEntry(new PelEntryAscii(PelTag::DATE_TIME, $date_time));
  $ifd0->addEntry(new PelEntryAscii(PelTag::IMAGE_DESCRIPTION, $description));

  _addGPSInformation($ifd0, $latitude, $longitude, $altitude);

  file_put_contents($output, $jpeg->getBytes());
}
```

**Comment by obelpair** [comment]
Hi Andrei-Robert,

I tried PEL last week for another issue concerning dates in my photo library, and maybe I found something that could help you for the **SubjectLocation** tag.

Examples describe tags that are located in the 0th IFD (DateTime, ImageDescription...) that you can reach directly using ```$idf0->addEntry()``` to write them or ```$ifd0->getEntry()``` to read them. But SubjectLocation (as DateTimeOriginal and DateTimeDigitized that were my concerns...) is located *in a different IFD*, which is called the EXIF IFD. 
After many tries I finally succeeded using : 

			$exifIfd = $ifd0->getSubIfd(PelIfd::EXIF);
			if ($exifIfd != null) {
			 $entry = $exifIfd->getEntry(PelTag::DATE_TIME_ORIGINAL);
			 if ($entry != null) {
		    	  $time = $entry->getValue();
		    	 }
			}

So, to access SubjectLocation I think the same code should work :

			$exifIfd = $ifd0->getSubIfd(PelIfd::EXIF);
			if ($exifIfd != null) {
			 $entry = $exifIfd->getEntry(PelTag::SUBJECT_LOCATION);
			 if ($entry != null) {
		    	  $subjectLocation = $entry->getValue();
		    	 }
			}

If your goal is to *add* a SubjectLocation tag, I think you could try something like : 

			$exifIfd = new PelIfd(PelIfd::EXIF);
			$ifd0->addSubIfd($exifIfd);
			$exifIfd->addEntry(new PelEntryShort(PelTag::SUBJECT_LOCATION, $subjectLocation));

I haven't tested this last part, sorry if I'm wrong.
Hope this will help.
Original documentation of the (dead) EXIF standard is available for example here : 
http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

Regards,
Olivier

**Comment by rusuandreirobert** [comment]
Hello Oliver, thanks for mentioning this, but I eventually had it working properly using IPTC data over my JPG, and I achieved exactly what I need in the end, thanks for mentioning this also, it helps.

**Comment by lsolesen** [comment]
@rusuandreirobert So you solved your issue?
