### ISSUE TITLE
Problem with - pel debug equal true

### ISSUE THREAD

**Issue by rocbar** [lsolesen/pel#44]
From the pel examples folder, I was testing the edit-description.php script which produced a error "Cannot access private property Pel::$debug in C:\pel\examples\edit-description.php on line 62". Is the code meant to be public instead of private on line 59 (`private static $debug = false;`) in the Pel.php class? However, I have changed line 59 to public and the code worked. Could it be that line 62 of the file "edit-description.php" code should have been `Pel::setDebug(true);` instead of changing the code on line 59 of Pel.php `private static $debug = false;` to public? I am working with PHP 5.6.13 version. I think this may be a bug, so what should be the best option here?

**Comment by lsolesen** [comment]
Best option is to try to fix it and make a pull request. If you can start
by making a failing test and then fix the issue so the test passes
afterwards.

Try to run the test suite to see wheter that passes for you?
Den 09/02/2016 00.25 skrev "rocbar" <notifications@github.com>:
