### ISSUE TITLE
adding exif to a tiff image

### ISSUE THREAD

**Issue by swarminfo** [lsolesen/pel#51]
Hello,

I am trying to run the examples given in https://github.com/lsolesen/pel/blob/master/examples/edit-description.php with a tiff image. It outputs an error : 

PHP Fatal error:  Call to undefined method lsolesen\pel\PelTiff::saveFile()

Is there a way to save the modified tiff file ? I tried with $tiff->getBytes but it doesn't seem to return the whole image.

Thank you

**Comment by lsolesen** [comment]
Seems that this method is in a pull request. https://github.com/lsolesen/pel/pull/42. I am not quite sure how it made it into the examples file. But the pull request seems reasonable. What do you say @weberhofer?

**Comment by mondrake** [comment]
This is fixed by https://github.com/lsolesen/pel/pull/84 I think.

**Comment by weberhofer** [comment]
Thanks for notification. I think you are right: This is fixed by #84
