### ISSUE TITLE
Tagging messed up

### ISSUE THREAD

**Issue by lsolesen** [lsolesen/pel#53]
We introduced namespaces somewhere between 0.9.2 and 0.9.3. We should really retag the latest releases to 0.10.0. What do you @robinlehrmann and @weberhofer say?

**Comment by weberhofer** [comment]
Definitely. I didn't tag it because I wasn't sure if everything is ok; as the tool I'm using pel is now working for several month without any issues I think 0.10.0 could be tagged.

**Comment by lsolesen** [comment]
Thought more about it. We cannot withdraw a tagged version, if people are using it. I've created a pull request https://github.com/lsolesen/pel/pull/54 with updated changelog and I've added notes to the releases https://github.com/lsolesen/pel/releases. Next version should be 0.10.0.
