### ISSUE TITLE
adding random location data for multiple images

### ISSUE THREAD

**Issue by aybekckaya** [lsolesen/pel#59]
I have used 'pel' in one of my projects  and needed to modify the code in gps.php file. I had to collect images in input folder , then it is needed to add random location data for each image . I will open a pull request for this addition . I guess there will be developers who needs this functionality. 
  @Isolesen : Thanks for your great job .

**Comment by lsolesen** [comment]
Thanks for your interest and usage of PEL. Nice to see how people are using it. I closed the pull request, because it is outside the scope of PEL. Please see https://github.com/lsolesen/pel/pull/60
