### ISSUE TITLE
Remove autoload.php

### ISSUE THREAD

**Issue by lsolesen** [lsolesen/pel#63]
@weberhofer Do you use autoload.php or do you rely on Composer?

https://github.com/lsolesen/pel/blob/master/autoload.php

**Comment by lsolesen** [comment]
We should probably keep this in, as people might not be leveraging composer.

**Comment by weberhofer** [comment]
@lsolesen, sorry for the late response, haven't seen that. When I remember right, I used that to run the test cases when I introduced the namespaces. It's possibly not longer needed, you might remove it.
