### ISSUE TITLE
EXIF value misses the last character

### ISSUE THREAD

**Issue by svenbluege** [lsolesen/pel#77]
I use the following code snippet to read the camera model: 

```
<?php

setlocale(LC_ALL, '');

require_once '../autoload.php';
use lsolesen\pel\PelDataWindow;
use lsolesen\pel\PelJpeg;
use lsolesen\pel\PelTiff;
use lsolesen\pel\Pel;
use lsolesen\pel\PelTag;

$prog = array_shift($argv);
$file = $argv[0];;
Pel::setDebug(true);


$input_jpeg = new PelJpeg($file);

$app1 = $input_jpeg->getExif();

$tiff = $app1->getTiff();
$ifd0 = $tiff->getIfd();
echo $ifd0->getEntry(PelTag::MODEL);
```

The code returns this for the attached image file:

```
/> php dump-image.php D:\temp\event\test7\20161125_124812_p4101ldrnightstrong.jpg
  Tag: 0x0110 (Model)
    Format    : 2 (Ascii)
    Components: 21
    Value     : Canon EOS 5D Mark II
    Text      : Canon EOS 5D Mark II

```

As you can see, it states a Canon 5D Mark **II** but actually it is a 5D MK **III**. The last character got lost somehow. The same file works fine in other exif tools: 

![image](https://cloud.githubusercontent.com/assets/3834825/21619621/c896d598-d1f0-11e6-8b9d-a9c473585a09.png)

Do you have any clue what is wrong here? I'm a bit clueless here. 

![20161125_124812_p4101ldrnightstrong](https://cloud.githubusercontent.com/assets/3834825/21619490/2e4c86d6-d1f0-11e6-9918-41c7688ee561.jpg)

**Comment by lsolesen** [comment]
Could you make a pull request with your Test?

**Comment by svenbluege** [comment]
on its way :)

**Comment by svenbluege** [comment]
Awesome! Thank you!
